### PR TITLE
REVIEW: update binaryen to master

### PR DESCRIPTION
**Pull request by lqd**
I'm not sure I did it right so I wanted to check with you (added the remote, pulled and rebased): is this how a binaryen update should be done (or should somehow your "Build binaryen statically" commit have been rewritten to be the last commit maybe) ?
If that's the case I'll then do a PR on mir2wasm to update the module, and add the module validation (I think it's gonna work now). I'll then need to check-in with you regarding the preferred command-line flags we could use to 1) run the optimization passes (-O, --release), 2) run the interpreter — and possibly 3) a -o for the output file which might be required to be able to run those two previous commands
(all of those either by using the C api or running binaryen-shell after having copied its binary to the cargo build output dir)

### CODE REVIEW

**Comment by brson** [comment]
> I'm not sure I did it right so I wanted to check with you (added the remote, pulled and rebased): is this how a binaryen update should be done (or should somehow your "Build binaryen statically" commit have been rewritten to be the last commit maybe) ?

The final commit in this PR should contain my commit. You can easily add it by cherry-picking `git cherry-pick brson/master` then pushing again.

**Comment by kripken** [comment]
Actually isn't it ok as is? This would get merged, so it doesn't overwrite the static linking commit?

**Comment by brson** [comment]
@kripken Yes, if we merge it it will work fine, though with an ugly history (but also it will preserve the commit of the existing submodule - which is useful). It's not how I usually maintain forks, but it's nbd either way.

**Comment by brson** [comment]
We can clean up history in the future if it ever matters. Thanks @lqd !

**Comment by lqd** [comment]
@brson I will then try to cherry-pick the commit the next time I update binaryen :)

**Comment by lqd** [comment]
and yeah it looks like history is messed up here as master is "19 commits ahead, 19 commits behind WebAssembly:master". the cherry picking probably wouldn't have been enough right ? maybe it was the rebase we talked about on irc or something else, who knows, git is so hard to use :(

**Comment by lqd** [comment]
@brson @kripken how about removing the need for our forks altogether ? ie https://github.com/WebAssembly/binaryen/pull/610

**Comment by kripken** [comment]
Great, merged that PR.

I wonder though if we won't want a fork for other stuff. About the commits, I'm surprised it says "19 ahead, 19 behind" - that shouldn't happen with a merge I think, the individual non-merge commits should be identical. Unless we rebased after a new commit here? Avoiding rebasing could avoid that going forward. (And to fix the current issue, a one-time rebase on upstream should work, I think.)

**Pull request merged**
